#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "=== Running Pre Commit Pipeline. ==="
# ----------------------------------------------------------------

echo "Fixing Code Formatting w/ Prettier"
npx prettier --write .