name: Code Linting

on:
  push:
    branches: ['ALMP-**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Get cached dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true